---
title: "Thesis significance tests"
author: "Tim Schwarz"
date: "7 5 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Test for significance using H_0: p = 0.5, H_1: p > 0.5

effect of outcome on no_passes:
```{r}
n_lost = 120509
n_won = 126155
n = n_lost + n_won

sigma_hat = sqrt((0.5*0.5)/n)

sample_prop = n_won / (n)

z = (sample_prop - 0.5)/sigma_hat
p = pnorm(1-z)

string = paste0("z: ", round(z, 3), ' p: ', p)
print(string)
```

Test for significance using H_0: p = 0.5, H_1: p > 0.5

effect of game state on no_passes:
```{r}
n_leading = 76419
n_trailing = 85519
n = n_leading + n_trailing

sigma_hat = sqrt((0.5*0.5)/n)

sample_prop = n_trailing / (n)

z = (sample_prop - 0.5)/sigma_hat
p = pnorm(1-z)

string = paste0("z: ", round(z, 3), ' p: ', p)
print(string)
```
Test for significance using H_0: p = 0.5, H_1: p > 0.5

effect of outcome while game state = drawing on no_passes:
```{r}
n_drawing_won = 56289
n_drawing_lost = 47829
n = n_drawing_won + n_drawing_lost

sigma_hat = sqrt((0.5*0.5)/n)

sample_prop = n_drawing_won / (n)

z = (sample_prop - 0.5)/sigma_hat
p = pnorm(1-z)

string = paste0("z: ", round(z, 3), ' p: ', p)
print(string)
```



